Vagrant.configure("2") do |config|
  # first machine is a server machine
  config.vm.boot_timeout = 900
  config.vm.define "rel-filaS" do |server|
    server.vm.box = "ubuntu/focal64"
    server.vm.hostname = "rel-filaS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "rel-filaS"
      vb.memory = 2048
      vb.cpus = 2
    end
    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      curl -sfL https://get.k3s.io | sh -
    SHELL
    server.vm.provision "shell", inline: <<-SHELL
      while ! sudo kubectl get nodes; do sleep 2; done
      sudo kubectl apply -f /vagrant/flask-deployment.yaml
      while [ $(sudo kubectl get pods -l app=flask --no-headers 2>/dev/null | grep -c "Running") -lt 3 ]; do 
        sleep 5
      done
      sudo kubectl get pods -o wide > /vagrant/pods_status.txt
      sudo kubectl get svc > /vagrant/services_status.txt
    SHELL
  end
end