Vagrant.configure("2") do |config|
  # first machine is a server machine
  config.vm.define "rel-filaS" do |server|
    server.vm.box = "ubuntu/focal64"
    server.vm.hostname = "rel-filaS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "rel-filaS"
      vb.memory = 2048
      vb.cpus = 3
    end
    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      curl -sfL https://get.k3s.io | sh -
      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/node-token
    SHELL
  end

  # Second machine is a worker achine
  config.vm.define "rel-filaSW" do |worker|
    worker.vm.box = "ubuntu/focal64"
    worker.vm.hostname = "rel-filaSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "rel-filaSW"
      vb.memory = 1024
      vb.cpus = 2
    end
    worker.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      while [ ! -f /vagrant/node-token ]; do sleep 2; done
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /vagrant/node-token) sh -
    SHELL
  end

end
