apiVersion: v1
kind: Service
metadata:
  name: gitlab-webservice-nodeport
  namespace: gitlab
  labels:
    app: webservice
spec:
  type: NodePort
  ports:
    - port: 8181
      targetPort: 8181
      nodePort: 30082
      protocol: TCP
      name: http
  selector:
    app: webservice
    release: gitlab