apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:latest
          ports:
            - containerPort: 80
            - containerPort: 22
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://localhost:8181'
                gitlab_rails['initial_root_password'] = 'GitLabR00t@2024!'
                
                # Disable monitoring (newer syntax)
                prometheus_monitoring['enable'] = false
                
                # Disable other unnecessary services
                gitlab_kas['enable'] = false
                gitlab_pages['enable'] = false
                registry['enable'] = false
                
                # Reduce resource usage
                sidekiq['max_concurrency'] = 5
                puma['worker_processes'] = 2
                puma['min_threads'] = 1
                puma['max_threads'] = 2
                postgresql['shared_buffers'] = "128MB"
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: gitlab
spec:
  selector:
    app: gitlab
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022