    Vagrant.configure("2") do |config|
    # first machine is a server machine
    config.vm.boot_timeout = 900
    config.vm.define "rel-filaS" do |server|
        server.vm.box = "ubuntu/focal64"
        server.vm.hostname = "rel-filaS"
        server.vm.network "private_network", ip: "192.168.56.110"
        # server.hostsupdater.aliases = ["app1.com", "app2.com", "app3.com"]
        server.vm.provider "virtualbox" do |vb|
        vb.name = "rel-filaS"
        vb.memory = 2048
        vb.cpus = 2
        end
        server.vm.provision "shell", inline: <<-SHELL
        # Add Docker's official GPG key:
            sudo apt-get update
            sudo apt-get install ca-certificates curl
            sudo install -m 0755 -d /etc/apt/keyrings
            sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
            sudo chmod a+r /etc/apt/keyrings/docker.asc

            echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            sudo apt-get update
            sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
            sudo usermod -aG docker vagrant
        SHELL
        server.vm.provision "shell", inline: <<-SHELL
            # curl -sfL https://get.k3s.io | sh -
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

            sleep 10
            k3d cluster create popo1 --agents 4 
            sudo kubectl get nodes > /vagrant/nodes_status.txt
        SHELL
    end
    end